### ISSUE TITLE
acc

### ISSUE THREAD

**Issue by cuzyoong** [paradise6/DetectMaliciousURL#1]
求问。。。windows下跑完acc为啥=1...

**Comment by cwellszhang** [comment]
为了方便测试我把数据量限制在1000条数据，把限制去掉就行了

**Comment by cuzyoong** [comment]
去掉限制是不是台机跑不动了要。。我把限制改成10000，跑出来acc好像还是1。。。

**Comment by cuzyoong** [comment]
![Uploading image.png…]()

**Comment by cuzyoong** [comment]
能不能给个qq号。。。。
